# This is a basic workflow to help you get started with Actions

name: Integración y entrega continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      MY VAR: "PRESENTACION"
      nombres: "Beltran"
      apellidos: "Quispe Salvia"
      edad: 45

      datosGerales: "Carrera de Ingeniería de Sistemas"

      user: ${{secrets.USER}} 
      password: ${{secrets.PASSWORD}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # PRESENTACION
      - name: Impresión de PRESENTACION
        run: |
          echo "La variable de entorno es: $MY_VAR"
          echo "Mi nombre es: ${{env.nombres}}"
          echo "Mis apellidos son: ${{env.apellidos}}"
          echo "Mi edad es: ${{env.edad}}"

      # DATOS GENERALES
      - name: Impresión de DATOS GENERALES
        run: |
          echo "La variable de entorno es: $MY_VAR"
          echo "Estudiante de : ${{env.datosGerales}}"
      
      # VARIABLES DE ENTORNO SECRETAS
      - name: Impresión de VARIABLES DE ENTORNO SECRETAS
        run: |
          echo "Usuario : ${{env.user}}"
          echo "Contraseña : ${{env.password}}"
        
      # VARIABLE ABIERTA
      - name: Impresión de VARIABLE ABIERTA
        run: |
          echo "Vesion de mi proyecto : ${{vars.VERSION_DE_MI_PROYECTO}}"